# Generated by Django 5.0.1 on 2024-02-08 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('umbrella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('studentID', models.IntegerField(default=0, unique=True)),
                ('studentCard', models.ImageField(upload_to='media/')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('umbrella', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='umbrella.umbrella')),
            ],
        ),
    ]
