# Generated by Django 5.0.1 on 2024-02-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentCard',
            field=models.ImageField(upload_to='profile/<django.db.models.fields.IntegerField>'),
        ),
    ]
