# Generated by Django 5.0.1 on 2024-05-12 23:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(default=0, unique=True)),
                ('withdrawal_reason', models.CharField(choices=[('수량', '우산 수량이 적어서 사용을 잘 안해요.'), ('관리', '우산 관리가 잘 안되어 사용할 수 없어요.'), ('새계정', '새 계정을 만들고 싶어요.'), ('기타', '기타사항 (직접 입력)')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('withdrawal_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 5, 19, 23, 42, 54, 660042))),
            ],
        ),
    ]
