# Generated by Django 5.0.1 on 2024-02-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default='01011112222', max_length=20),
            preserve_default=False,
        ),
    ]
