# Generated by Django 5.0.1 on 2024-03-24 17:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('return_due_date', models.DateTimeField(default=datetime.datetime(2024, 3, 27, 17, 9, 1, 275583))),
                ('rental_period', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='rent_images/')),
                ('is_disabled', models.BooleanField(default=False)),
                ('extension_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Umbrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('has_issue', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('명신관', 1), ('순헌관', 2), ('학생회관', 3), ('도서관', 4), ('음대', 5), ('백주년기념관', 6)], default=4, max_length=20)),
            ],
        ),
    ]
