# Generated by Django 5.0.1 on 2024-02-08 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Umbrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('명신관', '명신관'), ('순헌관', '순헌관'), ('학생회관', '학생회관'), ('도서관', '도서관')], default='도서관', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_data', models.DateTimeField()),
                ('return_due_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('umbrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umbrella.umbrella')),
            ],
        ),
    ]
