# Generated by Django 5.0.1 on 2024-02-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='return_data',
            new_name='return_date',
        ),
    ]
