# Generated by Django 5.0.1 on 2024-02-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrella',
            name='location',
            field=models.CharField(choices=[('명신관', '명신관'), ('순헌관', '순헌관'), ('학생회관', '학생회관'), ('도서관', '도서관')], default='도서관', max_length=20),
        ),
    ]
