# Generated by Django 5.0.1 on 2024-03-24 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 17, 12, 36, 99894)),
        ),
    ]
