# Generated by Django 5.0.1 on 2024-02-10 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0007_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rental_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 17, 3, 3, 608787)),
        ),
    ]
