# Generated by Django 5.0.1 on 2024-02-10 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0008_rent_rental_period_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='rental_period',
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 17, 22, 52, 206283)),
        ),
    ]
