# Generated by Django 5.0.1 on 2024-02-10 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0014_alter_rent_rental_period_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 20, 3, 28, 717427)),
        ),
        migrations.AlterField(
            model_name='umbrella',
            name='location',
            field=models.CharField(choices=[('명신관', 1), ('순헌관', 2), ('학생회관', 3), ('도서관', 4), ('음대', 5), ('백주년기념관', 6)], default=4, max_length=20),
        ),
    ]
