# Generated by Django 5.0.1 on 2024-02-10 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0015_alter_rent_return_due_date_alter_umbrella_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 20, 36, 59, 629212)),
        ),
    ]
