# Generated by Django 5.0.1 on 2024-02-11 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0017_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 23, 29, 59, 375876)),
        ),
    ]
