# Generated by Django 5.0.1 on 2024-02-14 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0019_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(default=1, upload_to='rent_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 0, 45, 8, 871453)),
        ),
    ]
