# Generated by Django 5.0.1 on 2024-03-10 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0020_rent_image_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 23, 13, 1, 608143)),
        ),
    ]
