# Generated by Django 5.0.1 on 2024-03-24 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0022_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='extension_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 16, 33, 58, 612609)),
        ),
    ]
