# Generated by Django 5.0.1 on 2024-03-24 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0024_alter_rent_return_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrella',
            name='has_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 16, 44, 55, 948021)),
        ),
    ]
