# Generated by Django 5.0.1 on 2024-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmbrellaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('분실', '우산을 분실했어요'), ('QR', 'QR코드가 파손되었어요'), ('파손', '우산이 부러졌어요'), ('기타', '기타사항 (직접 입력)')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
