# Generated by Django 5.0.1 on 2024-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellareport',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
