# Generated by Django 5.0.1 on 2024-03-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypage', '0001_initial'),
        ('umbrella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellareport',
            name='umbrella',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umbrella.umbrella'),
        ),
    ]
